services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: "no"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./rules:/var/lib/suricata/rules
      - suricata-logs:/var/log/suricata
      - suricata-run:/var/run/suricata
      - ../threat/pcaps:/pcaps:ro    # ← mount your PCAP folder
    command: -r /pcaps/2025-06-12-traffic-analysis-ex.pcap --set "vars.address-groups.HOME_NET=[192.168.1.0/24]"

volumes:
  suricata-logs:
  suricata-run:
