{
 "title": "Tablero 2: Seguridad y Alertas",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Alertas R1-R6 por hora",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(signature) (count_over_time({job=\"suricata_alerts\"} |= \"R\" [1h]))"
    }
   ]
  },
  {
   "title": "Intentos SSH (R3) en Tiempo Real",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"suricata_alerts\"} |= \"R3\" [1m]) "
    }
   ]
  },
  {
   "title": "Alertas Críticas (R6)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"suricata_alerts\"} |= \"R6\""
    }
   ]
  },
  {
   "title": "Conteo de Alertas por Regla",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(count_over_time({job=\"suricata_alerts\"} [1h]))"
    }
   ]
  },
  {
   "title": "Distribución de Severidad",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(severity) (count_over_time({job=\"suricata_alerts\"} [24h]))"
    },
    {
     "direction": "backward",
     "expr": "sum by(severity) (count_over_time({job=\"suricata_alerts\"} [1m]))"
    }
   ]
  },
  {
   "title": "Últimas 20 Alertas",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"suricata_alerts\"} | line_format \"{{.signature}}\""
    }
   ]
  },
  {
   "title": "Alertas en el Tiempo por Severidad",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(severity) (count_over_time({job=\"suricata_alerts\"} [1h]))"
    }
   ]
  }
 ]
}