{
 "title": "Prueba de Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(src_ip) (count_over_time({job=\"suricata\"} [5m])))"
    }
   ]
  },
  {
   "title": "Volumen de eventos por fuente",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(job) (count_over_time({job=~\"suricata|wazuh|docker\"} [1m]))"
    }
   ]
  },
  {
   "title": " Tráfico Northbound vs Southbound (Serie de tiempo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"suricata\"} |= \"10.0.2.\" [1m])",
     "legendFormat": "Northbound (192.168.0.0/24)"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"suricata\"} |= \"192.168.0.\" [1m])",
     "legendFormat": "Southbound (10.0.2.0/24)"
    }
   ]
  },
  {
   "title": " Alertas de Wazuh",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"wazuh\"}"
    }
   ]
  },
  {
   "title": "Eventos por severidad (últimos 5 min)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(severity) (count_over_time({job=~\"suricata|wazuh\"} [5m]))"
    }
   ]
  },
  {
   "title": "Alertas de Suricata",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"suricata\"}"
    }
   ]
  }
 ]
}