{
 "title": "ARP Spoofing",
 "tags": [
  "zeek",
  "arp",
  "spoofing",
  "loki",
  "thesis"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Loki Datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Estado actual",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"zeek_alerts\"} |= \"MANY_TO_ONE_MAC_CLAIM\" [1m]))"
    }
   ]
  },
  {
   "title": "Alertas MANY_TO_ONE (15m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"zeek_alerts\", filename=\"/var/log/zeek/arp_detec.log\"} |= \"MANY_TO_ONE_MAC_CLAIM\" [$__range]))"
    }
   ]
  },
  {
   "title": "Detecciones ARP Spoofing en el tiempo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"zeek_alerts\"} |= \"MANY_TO_ONE_MAC_CLAIM\" [1m]))"
    }
   ]
  },
  {
   "title": "Logs de Zeek ARP",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"zeek_alerts\"} |= \"MANY_TO_ONE_MAC_CLAIM\""
    }
   ]
  }
 ]
}