{
 "title": "Tablero 3: Monitoreo de Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Evolución de Alertas en el Tiempo",
   "type": "timeseries",
   "description": "Volumen de alertas por severidad",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(severity) (count_over_time({job=\"suricata_alerts\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Top 10 IPs Atacantes",
   "type": "bargauge",
   "description": "IPs de origen con más alertas en las últimas 24 horas",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(src_ip) (count_over_time({job=\"suricata_alerts\"} | json [24h]))"
    }
   ]
  },
  {
   "title": "Conexiones a IPs Sospechosas",
   "type": "timeseries",
   "description": "IPs destino con más alertas en las últimas 24 horas",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(signature) (count_over_time({job=\"suricata_alerts\"} [$__range]))"
    }
   ]
  }
 ]
}