services:
  zeek:
    container_name: zeek
    image: zeek/zeek:latest
    restart: "no"          # don't restart, just run once and exit cleanly

    network_mode: host

    cap_add:
      - NET_ADMIN
      - NET_RAW

    volumes:
      - ./logs:/usr/local/zeek/logs
      - ./pcaps:/pcaps

    working_dir: /usr/local/zeek/logs

    command: zeek -r /pcaps/test.pcap local
