services:
  zeek:
    container_name: zeek
    image: zeek/zeek:latest
    restart: "no"

    network_mode: host

    cap_add:
      - NET_ADMIN
      - NET_RAW

    volumes:
      - ./logs:/usr/local/zeek/logs
      - ./pcaps:/pcaps

    working_dir: /usr/local/zeek/logs

    command: zeek -r /pcaps/2025-06-13-traffic-analysis-exercise.pcap local
